### ISSUE TITLE
ch02: Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. 

### ISSUE THREAD

**Issue by donhuvy** [PacktPublishing/Hands-On-Software-Architecture-with-CSharp-8#1]
I am using Visual Studio 2019 Community edition, dotNET Core 3 preview.
I press F5, see error
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).
  Source=Microsoft.AspNetCore.Mvc.Core
  StackTrace:
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at scalability_sample.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in E:\source_code\github.com\Hands-On-Software-Architecture-with-CSharp-8\ch02\scalability-sample\Startup.cs:line 61
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
```

![image](https://user-images.githubusercontent.com/1328316/63312489-ea189380-c32b-11e9-95c6-b69360c10e9f.png)

**Comment by gabrielbaptista** [comment]
ch02 Sample code was written for .NET Core 2.2. I have changed now for .NET Core 3.0.

**Comment by donhuvy** [comment]
thank you!
